version : '3'
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    container_name: db_mailing
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: mailing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - mailing-networks

  redis:
    image: redis
    container_name: redis_mailing
    ports:
      - 6380:6379
    networks:
      - mailing-networks


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py init_database && python manage.py run -h 0.0.0.0"
    container_name: backend_mailing
    ports:
      - 5000:5000
    networks:
      - mailing-networks
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis

  worker:
    build:
        context: .
        dockerfile: Dockerfile
    command: bash -c "celery -A scheduler.main.celery_app worker --loglevel=INFO"
    container_name: worker_mailing
    networks:
      - mailing-networks
    depends_on:
      - backend
      - redis

volumes:
    db:

networks:
  mailing-networks:
    driver: bridge